title: Asura Engine Development
description: Development of the Asura Game Engine, from scratch!
show_downloads: true
theme: jekyll-theme-minimal
github:
  repository_url: https://github.com/shreejitmurthy/AsuraEngine
  repository_nwo: shreejitmurthy/AsuraEngine